### ISSUE TITLE
compute_geodesic_distances() returns ptu_dists matrix filled with 0.0 or NaNs

### ISSUE THREAD

**Issue by plelievre** [mbudnins/parallel_transport_unfolding#1]
First, thank you for this great tool !

Depending on seeds and different parameter configurations, I am running quite often into this issue :
Computed `self.ptu_dists` is filled with 0.0 or NaNs. Here is the minimal setup.

```python
import numpy as np
from parallel_transport_unfolding.ptu import PTU

n_samples = 10
n_dims = 8
n_neighbors = 3
seed = 100

x_tr = np.random.default_rng(seed=seed).standard_normal(
    size=(n_samples, n_dims))
x_tr = x_tr / np.linalg.norm(x_tr, axis=1, keepdims=True)
ptu = PTU(
    X=x_tr, n_neighbors=n_neighbors, geod_n_neighbors=n_neighbors,
    embedding_dim=n_dims)
ptu.compute_geodesic_distances()
print(ptu.ptu_dists)
```
```
[[ 0. nan nan nan nan nan nan nan nan nan]
 [nan  0. nan nan nan nan nan nan nan nan]
 [nan nan  0. nan nan nan nan nan nan nan]
 [nan nan nan  0. nan nan nan nan nan nan]
 [nan nan nan nan  0. nan nan nan nan nan]
 [nan nan nan nan nan  0. nan nan nan nan]
 [nan nan nan nan nan nan  0. nan nan nan]
 [nan nan nan nan nan nan nan  0. nan nan]
 [nan nan nan nan nan nan nan nan  0. nan]
 [nan nan nan nan nan nan nan nan nan  0.]]
```

**Comment by mbudnins** [comment]
Thank you!

Hmm, your example works fine most of the time on my machine and returns the expected distance matrix, but every once in a while it does return zeros and NaNs. I have not seen such behavior before, but it looks like it could be a memory issue?

I will look into it this week.

**Comment by mbudnins** [comment]
I think I know what is going on.

Assume we have a manifold of dimension `d` living in `D` dimensional space and it is sampled by a set of N points. Let `X` be `N` by `D` matrix representing those points. (In your example, `N=10, D=8, d=8`).

Short version: `geod_n_neighbors` parameter should be larger or equal to the dimension `d` of our manifold. If you set `geod_n_neighbors=8`, everything works.

Long version: the `geod_n_neighbors` parameter is used to sample a 'geodesic neighborhood' on our manifold around every point. After that, this geodesic neighborhood is used to approximate a local tangent space (of dimension `d`) to the manifold via SVD (via Lapack). In particular, it assumes that the geodesic neighborhood matrix has at least `d` non-zero singular values; associated `d` singular vectors are used as basis of the local tangent space.

In the example above, each geodesic neighborhood is 4x8, and it only has 4 left singular vectors (since geod_n_neighbors=3 and we include the point itself). It's not sufficient to compute an 8-dimensional tangent space. In practice, it grabs 4 left singular vectors and tries to take 4 more from the nearby memory. Therefore the last 4 have some random values and they eventually lead to NaNs or zeros.

I will add a check to make sure `geod_n_neighbors >= d` and also additional logic to prevent it from looking at memory it should not be looking at.

P.S. Another scenario in which Dijkstra and PTU algorithms can return NaN/infinite values is the case of several connected components, i.e. when your graph has vertices that are not connected by any path. In particular, it can happen when `n_neighbors` is small. I might add a check that computes the number of connected components in the future.

**Comment by plelievre** [comment]
Thank you for your extended explanation. It completely makes sense.

**Comment by mbudnins** [comment]
Commit https://github.com/mbudnins/parallel_transport_unfolding/commit/a8cf56fa6c9d1bf212cb1fe3aec7851378a83811 should resolve this issue.
